mklink /D complete-app\node_modules ..\node_modules
mklink /D react-sandbox\node_modules ..\node_modules

mklink /D lesson-6\node_modules ..\node_modules
mklink /D lesson-7\node_modules ..\node_modules
mklink /D lesson-8\node_modules ..\node_modules
mklink /D lesson-9\node_modules ..\node_modules
mklink /D lesson-10\node_modules ..\node_modules
mklink /D lesson-11\node_modules ..\node_modules
mklink /D lesson-12\node_modules ..\node_modules
mklink /D lesson-13\node_modules ..\node_modules
mklink /D lesson-17\node_modules ..\node_modules
mklink /D lesson-18\node_modules ..\node_modules
mklink /D lesson-19\node_modules ..\node_modules
mklink /D lesson-20\node_modules ..\node_modules
mklink /D lesson-21\node_modules ..\node_modules
mklink /D lesson-22\node_modules ..\node_modules
mklink /D lesson-23\node_modules ..\node_modules
mklink /D lesson-24\node_modules ..\node_modules
mklink /D lesson-25\node_modules ..\node_modules
mklink /D lesson-26\node_modules ..\node_modules
mklink /D lesson-27\node_modules ..\node_modules
mklink /D lesson-28\node_modules ..\node_modules
mklink /D lesson-29\node_modules ..\node_modules
mklink /D lesson-30\node_modules ..\node_modules
